import { defineConfig } from 'vitest/config';
import react from '@vitejs/plugin-react';
import tsconfigPaths from 'vite-tsconfig-paths';

export default defineConfig({
  plugins: [react(), tsconfigPaths()],
  test: {
    globals: true,
    environment: 'jsdom',
    setupFiles: ['./vitest.setup.ts'],
    include: ['**/*.test.(ts|tsx)'],
    exclude: ['node_modules', 'dist', '.idea', '.git'],
    coverage: {
      reporter: ['text', 'json', 'html'],
      all: true,
      include: ['components/**/*.{ts,tsx}', 'hooks/**/*.{ts,tsx}', 'utils/**/*.{ts,tsx}'],
      exclude: [
        '**/*.d.ts',
        '**/index.ts',
        '**/types.ts',
        '**/constants.ts',
        '**/*.stories.tsx',
        '**/*.test.(ts|tsx)',
        '**/__mocks__/**',
        '**/__tests__/**',
        '**/valid_tsx/**',
        '**/ui/**',
        '**/common/**',
        '**/stories/**',
        '**/node_modules/**',
        '**/dist/**',
        '**/test-utils.tsx',
        '**/vitest.setup.ts',
        '**/src/viewRegistry.ts',
        '**/App.tsx',
        '**/vite-env.d.ts',
        '**/index.tsx',
        '**/index.js',
        '**/index.css',
        '**/types/generated/**',
        '**/api/**',
        '**/contexts/**',
        '**/data/**',
        '**/lib/**',
        '**/services/**',
        '**/valid_tsx/**',
        '**/schemas/**',
        '**/responses/**',
        '**/security/**',
        '**/parameters/**',
        '**/file\uFFFD/**',
      ],
    },
  },
});