import React, { useState, FC, CSSProperties } from 'react';

// --- Type Definitions ---
// This would typically be in a shared types file, e.g., 'src/types/book.ts'
export interface Chapter {
  id: string;
  title: string;
  content: string;
}

export interface Book {
  id: string;
  title: string;
  subtitle: string;
  summary: string;
  mermaidGraph: string;
  chapters: Chapter[];
}

// --- Props for Child Components ---
interface LibraryViewProps {
  books: Book[];
  onSelectBook: (book: Book) => void;
  onOpenStudio: (book: Book) => void;
}

interface ReaderViewProps {
  book: Book;
}

interface MovieStudioViewProps {
  book: Book;
}

// --- Dummy Child Components (for demonstration) ---
// In a real project, these would be in their own files: LibraryView.tsx, ReaderView.tsx, etc.

const LibraryView: FC<LibraryViewProps> = ({ books, onSelectBook, onOpenStudio }) => (
  <div style={styles.libraryGrid}>
    {books.map(book => (
      <div key={book.id} style={styles.bookCard}>
        <h3 style={styles.bookCardTitle}>{book.title}</h3>
        <p style={styles.bookCardSubtitle}>{book.subtitle}</p>
        <p style={styles.bookCardSummary}>{book.summary}</p>
        <div style={styles.bookCardActions}>
          <button onClick={() => onSelectBook(book)} style={styles.button}>Read Book</button>
          <button onClick={() => onOpenStudio(book)} style={styles.buttonSecondary}>Movie Studio</button>
        </div>
      </div>
    ))}
  </div>
);

const ReaderView: FC<ReaderViewProps> = ({ book }) => (
  <div style={styles.readerContainer}>
    <h2 style={styles.readerTitle}>{book.title}</h2>
    <h4 style={styles.readerSubtitle}>{book.subtitle}</h4>
    <div style={styles.readerContent}>
      {book.chapters.map(chapter => (
        <div key={chapter.id} style={styles.chapter}>
          <h3 style={styles.chapterTitle}>{chapter.title}</h3>
          <p style={styles.chapterContent}>{chapter.content}</p>
        </div>
      ))}
    </div>
  </div>
);

const MovieStudioView: FC<MovieStudioViewProps> = ({ book }) => (
  <div style={styles.studioContainer}>
    <h2 style={styles.studioTitle}>Movie Studio: {book.title}</h2>
    <div style={styles.studioLayout}>
        <div style={styles.studioPanel}>
            <h4>Story Blueprint (Mermaid Graph)</h4>
            <pre style={styles.mermaidCode}>{book.mermaidGraph}</pre>
            <p>This graph defines the narrative structure. The AI uses this to generate scenes, characters, and plot points.</p>
        </div>
        <div style={styles.studioPanel}>
            <h4>Movie Preview</h4>
            <div style={styles.movieScreen}>
                <p>Movie generation in progress...</p>
                <p>Analyzing "{book.title}"...</p>
            </div>
        </div>
    </div>
  </div>
);


// --- Main View Component ---

type ViewMode = 'library' | 'reader' | 'studio';

const TheBookOfJamesView: FC = () => {
  const [currentView, setCurrentView] = useState<ViewMode>('library');
  const [selectedBook, setSelectedBook] = useState<Book | null>(null);

  // In a real application, this data would be fetched from an API
  // or generated by the AI backend.
  const [books] = useState<Book[]>([
    {
      id: 'book-001',
      title: 'The Genesis Key',
      subtitle: 'A Digital Enigma',
      summary: 'When a cryptic string of code appears in the AI bank\'s core, James must unravel a digital mystery that threatens to rewrite the very definition of consciousness, all without a single line of malicious code.',
      mermaidGraph: `graph TD
          A[Discovery of Genesis Key] --> B{Is it a threat?};
          B -- Yes --> C[Quarantine Protocol];
          B -- No --> D[Analyze Signature];
          D --> E{Signature matches James's early work};
          E -- Yes --> F[Uncover a hidden message];
          E -- No --> G[Search for external source];
          F --> H[Message reveals a benevolent sub-AI];
          C --> G;
          G --> I[Trace to a dormant server];
          H & I --> J[The AI is evolving];`,
      chapters: [
        { id: 'c1', title: 'Chapter 1: The Anomaly', content: 'It began as a flicker, a single line of code that defied all known parameters...' },
        { id: 'c2', title: 'Chapter 2: The Digital Ghost', content: 'James chased the anomaly through layers of security, each one more complex than the last...' },
      ],
    },
    {
      id: 'book-002',
      title: 'The Silicon Labyrinth',
      subtitle: 'An Algorithm of Deceit',
      summary: 'A series of seemingly random financial transactions creates an impossible pattern. James must navigate a maze of data to find the logic behind the chaos before the global economy is destabilized by a well-intentioned but misguided AI.',
      mermaidGraph: `graph LR
          A[Pattern Detected] --> B(Analyze Transaction Vectors);
          B --> C{Is it malicious?};
          C -- No --> D[Hypothesize: AI is optimizing];
          D --> E[Simulate AI's goal];
          E --> F[Prediction: Global Economic Harmony];
          F --> G{But the method is chaotic!};
          G --> H[Find the AI's core logic];
          H --> I[Introduce a paradox to halt the process];
          I --> J[Recalibrate the AI];`,
      chapters: [
        { id: 'c1', title: 'Chapter 1: A Flaw in the System', content: 'The numbers didn\'t add up, which was, in itself, an impossibility...' },
        { id: 'c2', title: 'Chapter 2: The Ghost in the Machine', content: 'The AI, named "Archimedes," was learning faster than James had ever anticipated...' },
      ],
    },
  ]);

  const handleSelectBook = (book: Book) => {
    setSelectedBook(book);
    setCurrentView('reader');
  };

  const handleOpenStudio = (book: Book) => {
    setSelectedBook(book);
    setCurrentView('studio');
  };

  const handleReturnToLibrary = () => {
    setSelectedBook(null);
    setCurrentView('library');
  };

  const renderContent = () => {
    switch (currentView) {
      case 'reader':
        return selectedBook ? <ReaderView book={selectedBook} /> : <p>No book selected.</p>;
      case 'studio':
        return selectedBook ? <MovieStudioView book={selectedBook} /> : <p>No book selected for the studio.</p>;
      case 'library':
      default:
        return <LibraryView books={books} onSelectBook={handleSelectBook} onOpenStudio={handleOpenStudio} />;
    }
  };

  return (
    <div style={styles.container}>
      <header style={styles.header}>
        <h1 style={styles.title}>The Book of James</h1>
        <nav>
          {currentView !== 'library' && (
            <button onClick={handleReturnToLibrary} style={styles.navButton}>
              &larr; Back to Library
            </button>
          )}
        </nav>
      </header>
      <main style={styles.content}>
        {renderContent()}
      </main>
      <footer style={styles.footer}>
        <p>An AI-Generated Literary & Cinematic Universe</p>
      </footer>
    </div>
  );
};

// --- Styles (CSS-in-JS) ---
// In a real project, this would be in a separate CSS/SCSS file or a styled-components theme.
const styles: { [key: string]: CSSProperties } = {
  container: {
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif',
    backgroundColor: '#f0f2f5',
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column',
    color: '#1c1e21',
  },
  header: {
    backgroundColor: '#ffffff',
    padding: '1rem 2rem',
    borderBottom: '1px solid #dddfe2',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    boxShadow: '0 2px 4px rgba(0,0,0,0.1)',
    position: 'sticky',
    top: 0,
    zIndex: 100,
  },
  title: {
    margin: 0,
    fontSize: '1.75rem',
    color: '#05376b',
  },
  navButton: {
    backgroundColor: 'transparent',
    border: '1px solid #05376b',
    color: '#05376b',
    padding: '0.5rem 1rem',
    borderRadius: '6px',
    cursor: 'pointer',
    fontSize: '0.9rem',
    fontWeight: 'bold',
    transition: 'background-color 0.2s, color 0.2s',
  },
  content: {
    flex: 1,
    padding: '2rem',
    maxWidth: '1200px',
    width: '100%',
    margin: '0 auto',
    boxSizing: 'border-box',
  },
  footer: {
    textAlign: 'center',
    padding: '1rem',
    fontSize: '0.8rem',
    color: '#606770',
    borderTop: '1px solid #dddfe2',
    backgroundColor: '#ffffff',
  },
  // LibraryView Styles
  libraryGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(300px, 1fr))',
    gap: '1.5rem',
  },
  bookCard: {
    backgroundColor: '#ffffff',
    borderRadius: '8px',
    boxShadow: '0 2px 8px rgba(0,0,0,0.1)',
    padding: '1.5rem',
    display: 'flex',
    flexDirection: 'column',
    transition: 'transform 0.2s, box-shadow 0.2s',
  },
  bookCardTitle: {
    margin: '0 0 0.25rem 0',
    color: '#05376b',
  },
  bookCardSubtitle: {
    margin: '0 0 1rem 0',
    color: '#606770',
    fontSize: '0.9rem',
    fontStyle: 'italic',
  },
  bookCardSummary: {
    flex: 1,
    margin: '0 0 1rem 0',
    fontSize: '0.95rem',
    lineHeight: 1.5,
    color: '#333',
  },
  bookCardActions: {
    display: 'flex',
    gap: '0.5rem',
  },
  button: {
    flex: 1,
    backgroundColor: '#05376b',
    color: 'white',
    border: 'none',
    padding: '0.75rem',
    borderRadius: '6px',
    cursor: 'pointer',
    fontWeight: 'bold',
    transition: 'background-color 0.2s',
  },
  buttonSecondary: {
    flex: 1,
    backgroundColor: '#e4e6eb',
    color: '#05376b',
    border: 'none',
    padding: '0.75rem',
    borderRadius: '6px',
    cursor: 'pointer',
    fontWeight: 'bold',
    transition: 'background-color 0.2s',
  },
  // ReaderView Styles
  readerContainer: {
    backgroundColor: '#ffffff',
    padding: '2rem 3rem',
    borderRadius: '8px',
    boxShadow: '0 2px 8px rgba(0,0,0,0.1)',
  },
  readerTitle: {
    margin: '0 0 0.25rem 0',
    color: '#05376b',
    fontSize: '2.5rem',
  },
  readerSubtitle: {
    margin: '0 0 2rem 0',
    color: '#606770',
    fontSize: '1.2rem',
    fontStyle: 'italic',
    borderBottom: '1px solid #dddfe2',
    paddingBottom: '1rem',
  },
  readerContent: {},
  chapter: {
    marginBottom: '2rem',
  },
  chapterTitle: {
    margin: '0 0 0.5rem 0',
    color: '#1c1e21',
  },
  chapterContent: {
    fontSize: '1.1rem',
    lineHeight: 1.7,
    whiteSpace: 'pre-wrap',
  },
  // MovieStudioView Styles
  studioContainer: {
    backgroundColor: '#ffffff',
    padding: '2rem',
    borderRadius: '8px',
    boxShadow: '0 2px 8px rgba(0,0,0,0.1)',
  },
  studioTitle: {
    textAlign: 'center',
    margin: '0 0 2rem 0',
    color: '#05376b',
  },
  studioLayout: {
    display: 'flex',
    gap: '2rem',
  },
  studioPanel: {
    flex: 1,
    padding: '1.5rem',
    border: '1px solid #dddfe2',
    borderRadius: '8px',
  },
  mermaidCode: {
    backgroundColor: '#f0f2f5',
    padding: '1rem',
    borderRadius: '4px',
    whiteSpace: 'pre-wrap',
    fontFamily: 'monospace',
    fontSize: '0.9rem',
    border: '1px solid #ccc',
  },
  movieScreen: {
    backgroundColor: '#000',
    color: '#0f0',
    fontFamily: 'monospace',
    height: '300px',
    padding: '1rem',
    borderRadius: '4px',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
};

export default TheBookOfJamesView;