


import React, { useState, useEffect } from 'react';
import { useTheme } from '@mui/material/styles';
import {
  Box,
  CircularProgress,
  Typography,
  IconButton,
  Tooltip,
  useMediaQuery,
} from '@mui/material';
import {
  Zoom,
  useNodes,
  useEdges,
  useReactFlow,
  ReactFlowProvider,
  Controls,
  MiniMap,
  Background,
  NodeTypes,
  EdgeTypes,
  addEdge,
} from 'reactflow';
import 'reactflow/dist/style.css';
import {
  ChevronLeft,
  ChevronRight,
  Fullscreen,
  FullscreenExit,
} from '@mui/icons-material';
import {
  useStripeData,
  ResourceType,
  StripeResource,
  NodeData,
  EdgeData,
  isEdge,
  isNode,
} from '../hooks/useStripeData';
import {
  AccountNode,
  AccountLinkNode,
  ApplePayDomainNode,
  ApplicationFeeNode,
  AppsSecretNode,
  BalanceNode,
  BalanceTransactionNode,
  BankAccountNode,
  BillingPortalConfigurationNode,
  BillingPortalSessionNode,
  CapabilityNode,
  CardNode,
  CashBalanceNode,
  ChargeNode,
  CheckoutSessionNode,
  CountrySpecNode,
  CouponNode,
  CreditNoteNode,
  CreditNoteLineItemNode,
  CustomerNode,
  CustomerBalanceTransactionNode,
  CustomerCashBalanceTransactionNode,
  DeletedAccountNode,
  DeletedApplePayDomainNode,
  DeletedCouponNode,
  DeletedCustomerNode,
  DeletedDiscountNode,
  DeletedExternalAccountNode,
  DeletedInvoiceNode,
  DeletedInvoiceitemNode,
  DeletedPaymentSourceNode,
  DeletedPersonNode,
  DeletedPlanNode,
  DeletedProductNode,
  DeletedRadarValueListNode,
  DeletedRadarValueListItemNode,
  DeletedSubscriptionItemNode,
  DeletedTaxIdNode,
  DeletedTerminalConfigurationNode,
  DeletedTerminalLocationNode,
  DeletedTerminalReaderNode,
  DeletedTestHelpersTestClockNode,
  DeletedWebhookEndpointNode,
  DiscountNode,
  DisputeNode,
  EphemeralKeyNode,
  EventNode,
  ExchangeRateNode,
  ExternalAccountNode,
  FeeRefundNode,
  FileNode,
  FileLinkNode,
  FinancialConnectionsAccountNode,
  FinancialConnectionsAccountOwnerNode,
  FinancialConnectionsSessionNode,
  FundingInstructionsNode,
  IdentityVerificationReportNode,
  IdentityVerificationSessionNode,
  InvoiceNode,
  InvoiceitemNode,
  IssuingAuthorizationNode,
  IssuingCardNode,
  IssuingCardholderNode,
  IssuingDisputeNode,
  IssuingSettlementNode,
  IssuingTransactionNode,
  ItemNode,
  LineItemNode,
  LoginLinkNode,
  MandateNode,
  PaymentIntentNode,
  PaymentLinkNode,
  PaymentMethodNode,
  PaymentSourceNode,
  PayoutNode,
  PersonNode,
  PlanNode,
  PriceNode,
  ProductNode,
  PromotionCodeNode,
  QuoteNode,
  RadarEarlyFraudWarningNode,
  RadarValueListNode,
  RadarValueListItemNode,
  RefundNode,
  ReportingReportRunNode,
  ReportingReportTypeNode,
  ReviewNode,
  ScheduledQueryRunNode,
  SetupAttemptNode,
  SetupIntentNode,
  ShippingRateNode,
  SourceNode,
  SourceMandateNotificationNode,
  SourceTransactionNode,
  SubscriptionNode,
  SubscriptionItemNode,
  SubscriptionScheduleNode,
  TaxCodeNode,
  TaxIdNode,
  TaxRateNode,
  TerminalConfigurationNode,
  TerminalConnectionTokenNode,
  TerminalLocationNode,
  TerminalReaderNode,
  TestHelpersTestClockNode,
  TokenNode,
  TopupNode,
  TransferNode,
  TransferReversalNode,
  TreasuryCreditReversalNode,
  TreasuryDebitReversalNode,
  TreasuryFinancialAccountNode,
  TreasuryFinancialAccountFeaturesNode,
  TreasuryInboundTransferNode,
  TreasuryOutboundPaymentNode,
  TreasuryOutboundTransferNode,
  TreasuryReceivedCreditNode,
  TreasuryReceivedDebitNode,
  TreasuryTransactionNode,
  TreasuryTransactionEntryNode,
  WebhookEndpointNode,
  AccountNoticeNode,
  AccountSessionNode,
  ApplicationNode,
  BalanceSettingsNode,
  BillingAlertNode,
  BillingAlertTriggeredNode,
  BillingCreditBalanceSummaryNode,
  BillingCreditBalanceTransactionNode,
  BillingCreditGrantNode,
  BillingMeterNode,
  BillingMeterEventNode,
  BillingMeterEventAdjustmentNode,
  BillingMeterEventSummaryNode,
  CapitalFinancingOfferNode,
  CapitalFinancingSummaryNode,
  CapitalFinancingTransactionNode,
  ClimateOrderNode,
  ClimateProductNode,
  ClimateSupplierNode,
  ConfirmationTokenNode,
  CustomerSessionNode,
  DeletedApplicationNode,
  DeletedBankAccountNode,
  DeletedCardNode,
  DeletedPriceNode,
  DeletedProductFeatureNode,
  EntitlementsActiveEntitlementNode,
  EntitlementsActiveEntitlementSummaryNode,
  EntitlementsFeatureNode,
  FinancialConnectionsAccountInferredBalanceNode,
  FinancialConnectionsAccountOwnershipNode,
  FinancialConnectionsInstitutionNode,
  FinancialConnectionsTransactionNode,
  ForwardingRequestNode,
  FxQuoteNode,
  InvoicePaymentNode,
  InvoiceRenderingTemplateNode,
  IssuingCreditUnderwritingRecordNode,
  IssuingDisputeSettlementDetailNode,
  IssuingFraudLiabilityDebitNode,
  IssuingPersonalizationDesignNode,
  IssuingPhysicalBundleNode,
  IssuingTokenNode,
  MarginNode,
  OrderNode,
  PaymentAttemptRecordNode,
  PaymentIntentAmountDetailsLineItemNode,
  PaymentMethodConfigurationNode,
  PaymentMethodDomainNode,
  PaymentRecordNode,
  PrivacyRedactionJobNode,
  PrivacyRedactionJobValidationErrorNode,
  ProductFeatureNode,
  QuoteLineNode,
  QuotePreviewInvoiceNode,
  QuotePreviewSubscriptionScheduleNode,
  TaxAssociationNode,
  TaxCalculationNode,
  TaxCalculationLineItemNode,
  TaxFormNode,
  TaxRegistrationNode,
  TaxSettingsNode,
  TaxTransactionNode,
  TaxTransactionLineItemNode,
  TerminalReaderCollectedDataNode,
  TerminalOnboardingLinkNode,
  BillingAnalyticsMeterUsageNode,
  BillingAnalyticsMeterUsageRowNode,
  PaymentMethodBalanceNode,
  DelegatedCheckoutRequestedSessionNode,
  IdentityBlocklistEntryNode,
  TransitBalanceNode,
  IssuingProgramNode,
  BalanceTransferNode,
  RadarAccountEvaluationNode,
  ProductCatalogTrialOfferNode,
} from './nodes';
import {
  DefaultEdge,
  AccountEdge,
  AccountLinkEdge,
  ApplePayDomainEdge,
  ApplicationFeeEdge,
  AppsSecretEdge,
  BalanceEdge,
  BalanceTransactionEdge,
  BankAccountEdge,
  BillingPortalConfigurationEdge,
  BillingPortalSessionEdge,
  CapabilityEdge,
  CardEdge,
  CashBalanceEdge,
  ChargeEdge,
  CheckoutSessionEdge,
  CountrySpecEdge,
  CouponEdge,
  CreditNoteEdge,
  CreditNoteLineItemEdge,
  CustomerEdge,
  CustomerBalanceTransactionEdge,
  CustomerCashBalanceTransactionEdge,
  DeletedAccountEdge,
  DeletedApplePayDomainEdge,
  DeletedCouponEdge,
  DeletedCustomerEdge,
  DeletedDiscountEdge,
  DeletedExternalAccountEdge,
  DeletedInvoiceEdge,
  DeletedInvoiceitemEdge,
  DeletedPaymentSourceEdge,
  DeletedPersonEdge,
  DeletedPlanEdge,
  DeletedProductEdge,
  DeletedRadarValueListEdge,
  DeletedRadarValueListItemEdge,
  DeletedSubscriptionItemEdge,
  DeletedTaxIdEdge,
  DeletedTerminalConfigurationEdge,
  DeletedTerminalLocationEdge,
  DeletedTerminalReaderEdge,
  DeletedTestHelpersTestClockEdge,
  DeletedWebhookEndpointEdge,
  DiscountEdge,
  DisputeEdge,
  EphemeralKeyEdge,
  EventEdge,
  ExchangeRateEdge,
  ExternalAccountEdge,
  FeeRefundEdge,
  FileEdge,
  FileLinkEdge,
  FinancialConnectionsAccountEdge,
  FinancialConnectionsAccountOwnerEdge,
  FinancialConnectionsSessionEdge,
  FundingInstructionsEdge,
  IdentityVerificationReportEdge,
  IdentityVerificationSessionEdge,
  InvoiceEdge,
  InvoiceitemEdge,
  IssuingAuthorizationEdge,
  IssuingCardEdge,
  IssuingCardholderEdge,
  IssuingDisputeEdge,
  IssuingSettlementEdge,
  IssuingTransactionEdge,
  ItemEdge,
  LineItemEdge,
  LoginLinkEdge,
  MandateEdge,
  PaymentIntentEdge,
  PaymentLinkEdge,
  PaymentMethodEdge,
  PaymentSourceEdge,
  PayoutEdge,
  PersonEdge,
  PlanEdge,
  PriceEdge,
  ProductEdge,
  PromotionCodeEdge,
  QuoteEdge,
  RadarEarlyFraudWarningEdge,
  RadarValueListEdge,
  RadarValueListItemEdge,
  RefundEdge,
  ReportingReportRunEdge,
  ReportingReportTypeEdge,
  ReviewEdge,
  ScheduledQueryRunEdge,
  SetupAttemptEdge,
  SetupIntentEdge,
  ShippingRateEdge,
  SourceEdge,
  SourceMandateNotificationEdge,
  SourceTransactionEdge,
  SubscriptionEdge,
  SubscriptionItemEdge,
  SubscriptionScheduleEdge,
  TaxCodeEdge,
  TaxIdEdge,
  TaxRateEdge,
  TerminalConfigurationEdge,
  TerminalConnectionTokenEdge,
  TerminalLocationEdge,
  TerminalReaderEdge,
  TestHelpersTestClockEdge,
  TokenEdge,
  TopupEdge,
  TransferEdge,
  TransferReversalEdge,
  TreasuryCreditReversalEdge,
  TreasuryDebitReversalEdge,
  TreasuryFinancialAccountEdge,
  TreasuryFinancialAccountFeaturesEdge,
  TreasuryInboundTransferEdge,
  TreasuryOutboundPaymentEdge,
  TreasuryOutboundTransferEdge,
  TreasuryReceivedCreditEdge,
  TreasuryReceivedDebitEdge,
  TreasuryTransactionEdge,
  TreasuryTransactionEntryEdge,
  WebhookEndpointEdge,
  AccountNoticeEdge,
  AccountSessionEdge,
  ApplicationEdge,
  BalanceSettingsEdge,
  BillingAlertEdge,
  BillingAlertTriggeredEdge,
  BillingCreditBalanceSummaryEdge,
  BillingCreditBalanceTransactionEdge,
  BillingCreditGrantEdge,
  BillingMeterEdge,
  BillingMeterEventEdge,
  BillingMeterEventAdjustmentEdge,
  BillingMeterEventSummaryEdge,
  CapitalFinancingOfferEdge,
  CapitalFinancingSummaryEdge,
  CapitalFinancingTransactionEdge,
  ClimateOrderEdge,
  ClimateProductEdge,
  ClimateSupplierEdge,
  ConfirmationTokenEdge,
  CustomerSessionEdge,
  DeletedApplicationEdge,
  DeletedBankAccountEdge,
  DeletedCardEdge,
  DeletedPriceEdge,
  DeletedProductFeatureEdge,
  EntitlementsActiveEntitlementEdge,
  EntitlementsActiveEntitlementSummaryEdge,
  EntitlementsFeatureEdge,
  FinancialConnectionsAccountInferredBalanceEdge,
  FinancialConnectionsAccountOwnershipEdge,
  FinancialConnectionsInstitutionEdge,
  FinancialConnectionsTransactionEdge,
  ForwardingRequestEdge,
  FxQuoteEdge,
  InvoicePaymentEdge,
  InvoiceRenderingTemplateEdge,
  IssuingCreditUnderwritingRecordEdge,
  IssuingDisputeSettlementDetailEdge,
  IssuingFraudLiabilityDebitEdge,
  IssuingPersonalizationDesignEdge,
  IssuingPhysicalBundleEdge,
  IssuingTokenEdge,
  MarginEdge,
  OrderEdge,
  PaymentAttemptRecordEdge,
  PaymentIntentAmountDetailsLineItemEdge,
  PaymentMethodConfigurationEdge,
  PaymentMethodDomainEdge,
  PaymentRecordEdge,
  PrivacyRedactionJobEdge,
  PrivacyRedactionJobValidationErrorEdge,
  ProductFeatureEdge,
  QuoteLineEdge,
  QuotePreviewInvoiceEdge,
  QuotePreviewSubscriptionScheduleEdge,
  TaxAssociationEdge,
  TaxCalculationEdge,
  TaxCalculationLineItemEdge,
  TaxFormEdge,
  TaxRegistrationEdge,
  TaxSettingsEdge,
  TaxTransactionEdge,
  TaxTransactionLineItemEdge,
  TerminalReaderCollectedDataEdge,
  TerminalOnboardingLinkEdge,
  BillingAnalyticsMeterUsageEdge,
  BillingAnalyticsMeterUsageRowEdge,
  PaymentMethodBalanceEdge,
  DelegatedCheckoutRequestedSessionEdge,
  IdentityBlocklistEntryEdge,
  TransitBalanceEdge,
  IssuingProgramEdge,
  BalanceTransferEdge,
  RadarAccountEvaluationEdge,
  ProductCatalogTrialOfferEdge,
} from './edges';

const nodeTypes: NodeTypes = {
  account: AccountNode,
  account_link: AccountLinkNode,
  apple_pay_domain: ApplePayDomainNode,
  application_fee: ApplicationFeeNode,
  apps_secret: AppsSecretNode,
  balance: BalanceNode,
  balance_transaction: BalanceTransactionNode,
  bank_account: BankAccountNode,
  billing_portal_configuration: BillingPortalConfigurationNode,
  billing_portal_session: BillingPortalSessionNode,
  capability: CapabilityNode,
  card: CardNode,
  cash_balance: CashBalanceNode,
  charge: ChargeNode,
  checkout_session: CheckoutSessionNode,
  country_spec: CountrySpecNode,
  coupon: CouponNode,
  credit_note: CreditNoteNode,
  credit_note_line_item: CreditNoteLineItemNode,
  customer: CustomerNode,
  customer_balance_transaction: CustomerBalanceTransactionNode,
  customer_cash_balance_transaction: CustomerCashBalanceTransactionNode,
  deleted_account: DeletedAccountNode,
  deleted_apple_pay_domain: DeletedApplePayDomainNode,
  deleted_coupon: DeletedCouponNode,
  deleted_customer: DeletedCustomerNode,
  deleted_discount: DeletedDiscountNode,
  deleted_external_account: DeletedExternalAccountNode,
  deleted_invoice: DeletedInvoiceNode,
  deleted_invoiceitem: DeletedInvoiceitemNode,
  deleted_payment_source: DeletedPaymentSourceNode,
  deleted_person: DeletedPersonNode,
  deleted_plan: DeletedPlanNode,
  deleted_product: DeletedProductNode,
  deleted_radar_value_list: DeletedRadarValueListNode,
  deleted_radar_value_list_item: DeletedRadarValueListItemNode,
  deleted_subscription_item: DeletedSubscriptionItemNode,
  deleted_tax_id: DeletedTaxIdNode,
  deleted_terminal_configuration: DeletedTerminalConfigurationNode,
  deleted_terminal_location: DeletedTerminalLocationNode,
  deleted_terminal_reader: DeletedTerminalReaderNode,
  deleted_test_helpers_test_clock: DeletedTestHelpersTestClockNode,
  deleted_webhook_endpoint: DeletedWebhookEndpointNode,
  discount: DiscountNode,
  dispute: DisputeNode,
  ephemeral_key: EphemeralKeyNode,
  event: EventNode,
  exchange_rate: ExchangeRateNode,
  external_account: ExternalAccountNode,
  fee_refund: FeeRefundNode,
  file: FileNode,
  file_link: FileLinkNode,
  financial_connections_account: FinancialConnectionsAccountNode,
  financial_connections_account_owner: FinancialConnectionsAccountOwnerNode,
  financial_connections_session: FinancialConnectionsSessionNode,
  funding_instructions: FundingInstructionsNode,
  identity_verification_report: IdentityVerificationReportNode,
  identity_verification_session: IdentityVerificationSessionNode,
  invoice: InvoiceNode,
  invoiceitem: InvoiceitemNode,
  issuing_authorization: IssuingAuthorizationNode,
  issuing_card: IssuingCardNode,
  issuing_cardholder: IssuingCardholderNode,
  issuing_dispute: IssuingDisputeNode,
  issuing_settlement: IssuingSettlementNode,
  issuing_transaction: IssuingTransactionNode,
  item: ItemNode,
  line_item: LineItemNode,
  login_link: LoginLinkNode,
  mandate: MandateNode,
  payment_intent: PaymentIntentNode,
  payment_link: PaymentLinkNode,
  payment_method: PaymentMethodNode,
  payment_source: PaymentSourceNode,
  payout: PayoutNode,
  person: PersonNode,
  plan: PlanNode,
  price: PriceNode,
  product: ProductNode,
  promotion_code: PromotionCodeNode,
  quote: QuoteNode,
  radar_early_fraud_warning: RadarEarlyFraudWarningNode,
  radar_value_list: RadarValueListNode,
  radar_value_list_item: RadarValueListItemNode,
  refund: RefundNode,
  reporting_report_run: ReportingReportRunNode,
  reporting_report_type: ReportingReportTypeNode,
  review: ReviewNode,
  scheduled_query_run: ScheduledQueryRunNode,
  setup_attempt: SetupAttemptNode,
  setup_intent: SetupIntentNode,
  shipping_rate: ShippingRateNode,
  source: SourceNode,
  source_mandate_notification: SourceMandateNotificationNode,
  source_transaction: SourceTransactionNode,
  subscription: SubscriptionNode,
  subscription_item: SubscriptionItemNode,
  subscription_schedule: SubscriptionScheduleNode,
  tax_code: TaxCodeNode,
  tax_id: TaxIdNode,
  tax_rate: TaxRateNode,
  terminal_configuration: TerminalConfigurationNode,
  terminal_connection_token: TerminalConnectionTokenNode,
  terminal_location: TerminalLocationNode,
  terminal_reader: TerminalReaderNode,
  test_helpers_test_clock: TestHelpersTestClockNode,
  token: TokenNode,
  topup: TopupNode,
  transfer: TransferNode,
  transfer_reversal: TransferReversalNode,
  treasury_credit_reversal: TreasuryCreditReversalNode,
  treasury_debit_reversal: TreasuryDebitReversalNode,
  treasury_financial_account: TreasuryFinancialAccountNode,
  treasury_financial_account_features: TreasuryFinancialAccountFeaturesNode,
  treasury_inbound_transfer: TreasuryInboundTransferNode,
  treasury_outbound_payment: TreasuryOutboundPaymentNode,
  treasury_outbound_transfer: TreasuryOutboundTransferNode,
  treasury_received_credit: TreasuryReceivedCreditNode,
  treasury_received_debit: TreasuryReceivedDebitNode,
  treasury_transaction: TreasuryTransactionNode,
  treasury_transaction_entry: TreasuryTransactionEntryNode,
  webhook_endpoint: WebhookEndpointNode,
  account_notice: AccountNoticeNode,
  account_session: AccountSessionNode,
  application: ApplicationNode,
  balance_settings: BalanceSettingsNode,
  billing_alert: BillingAlertNode,
  billing_alert_triggered: BillingAlertTriggeredNode,
  billing_credit_balance_summary: BillingCreditBalanceSummaryNode,
  billing_credit_balance_transaction: BillingCreditBalanceTransactionNode,
  billing_credit_grant: BillingCreditGrantNode,
  billing_meter: BillingMeterNode,
  billing_meter_event: BillingMeterEventNode,
  billing_meter_event_adjustment: BillingMeterEventAdjustmentNode,
  billing_meter_event_summary: BillingMeterEventSummaryNode,
  capital_financing_offer: CapitalFinancingOfferNode,
  capital_financing_summary: CapitalFinancingSummaryNode,
  capital_financing_transaction: CapitalFinancingTransactionNode,
  climate_order: ClimateOrderNode,
  climate_product: ClimateProductNode,
  climate_supplier: ClimateSupplierNode,
  confirmation_token: ConfirmationTokenNode,
  customer_session: CustomerSessionNode,
  deleted_application: DeletedApplicationNode,
  deleted_bank_account: DeletedBankAccountNode,
  deleted_card: DeletedCardNode,
  deleted_price: DeletedPriceNode,
  deleted_product_feature: DeletedProductFeatureNode,
  entitlements_active_entitlement: EntitlementsActiveEntitlementNode,
  entitlements_active_entitlement_summary: EntitlementsActiveEntitlementSummaryNode,
  entitlements_feature: EntitlementsFeatureNode,
  financial_connections_account_inferred_balance: FinancialConnectionsAccountInferredBalanceNode,
  financial_connections_account_ownership: FinancialConnectionsAccountOwnershipNode,
  financial_connections_institution: FinancialConnectionsInstitutionNode,
  financial_connections_transaction: FinancialConnectionsTransactionNode,
  forwarding_request: ForwardingRequestNode,
  fx_quote: FxQuoteNode,
  invoice_payment: InvoicePaymentNode,
  invoice_rendering_template: InvoiceRenderingTemplateNode,
  issuing_credit_underwriting_record: IssuingCreditUnderwritingRecordNode,
  issuing_dispute_settlement_detail: IssuingDisputeSettlementDetailNode,
  issuing_fraud_liability_debit: IssuingFraudLiabilityDebitNode,
  issuing_personalization_design: IssuingPersonalizationDesignNode,
  issuing_physical_bundle: IssuingPhysicalBundleNode,
  issuing_token: IssuingTokenNode,
  margin: MarginNode,
  order: OrderNode,
  payment_attempt_record: PaymentAttemptRecordNode,
  payment_intent_amount_details_line_item: PaymentIntentAmountDetailsLineItemNode,
  payment_method_configuration: PaymentMethodConfigurationNode,
  payment_method_domain: PaymentMethodDomainNode,
  payment_record: PaymentRecordNode,
  privacy_redaction_job: PrivacyRedactionJobNode,
  privacy_redaction_job_validation_error: PrivacyRedactionJobValidationErrorNode,
  product_feature: ProductFeatureNode,
  quote_line: QuoteLineNode,
  quote_preview_invoice: QuotePreviewInvoiceNode,
  quote_preview_subscription_schedule: QuotePreviewSubscriptionScheduleNode,
  tax_association: TaxAssociationNode,
  tax_calculation: TaxCalculationNode,
  tax_calculation_line_item: TaxCalculationLineItemNode,
  tax_form: TaxFormNode,
  tax_registration: TaxRegistrationNode,
  tax_settings: TaxSettingsNode,
  tax_transaction: TaxTransactionNode,
  tax_transaction_line_item: TaxTransactionLineItemNode,
  terminal_reader_collected_data: TerminalReaderCollectedDataNode,
  terminal_onboarding_link: TerminalOnboardingLinkNode,
  billing_analytics_meter_usage: BillingAnalyticsMeterUsageNode,
  billing_analytics_meter_usage_row: BillingAnalyticsMeterUsageRowNode,
  payment_method_balance: PaymentMethodBalanceNode,
  delegated_checkout_requested_session: DelegatedCheckoutRequestedSessionNode,
  identity_blocklist_entry: IdentityBlocklistEntryNode,
  transit_balance: TransitBalanceNode,
  issuing_program: IssuingProgramNode,
  balance_transfer: BalanceTransferNode,
  radar_account_evaluation: RadarAccountEvaluationNode,
  product_catalog_trial_offer: ProductCatalogTrialOfferNode,
};

const edgeTypes: EdgeTypes = {
  default: DefaultEdge,
  account: AccountEdge,
  account_link: AccountLinkEdge,
  apple_pay_domain: ApplePayDomainEdge,
  application_fee: ApplicationFeeEdge,
  apps_secret: AppsSecretEdge,
  balance: BalanceEdge,
  balance_transaction: BalanceTransactionEdge,
  bank_account: BankAccountEdge,
  billing_portal_configuration: BillingPortalConfigurationEdge,
  billing_portal_session: BillingPortalSessionEdge,
  capability: CapabilityEdge,
  card: CardEdge,
  cash_balance: CashBalanceEdge,
  charge: ChargeEdge,
  checkout_session: CheckoutSessionEdge,
  country_spec: CountrySpecEdge,
  coupon: CouponEdge,
  credit_note: CreditNoteEdge,
  credit_note_line_item: CreditNoteLineItemEdge,
  customer: CustomerEdge,
  customer_balance_transaction: CustomerBalanceTransactionEdge,
  customer_cash_balance_transaction: CustomerCashBalanceTransactionEdge,
  deleted_account: DeletedAccountEdge,
  deleted_apple_pay_domain: DeletedApplePayDomainEdge,
  deleted_coupon: DeletedCouponEdge,
  deleted_customer: DeletedCustomerEdge,
  deleted_discount: DeletedDiscountEdge,
  deleted_external_account: DeletedExternalAccountEdge,
  deleted_invoice: DeletedInvoiceEdge,
  deleted_invoiceitem: DeletedInvoiceitemEdge,
  deleted_payment_source: DeletedPaymentSourceEdge,
  deleted_person: DeletedPersonEdge,
  deleted_plan: DeletedPlanEdge,
  deleted_product: DeletedProductEdge,
  deleted_radar_value_list: DeletedRadarValueListEdge,
  deleted_radar_value_list_item: DeletedRadarValueListItemEdge,
  deleted_subscription_item: DeletedSubscriptionItemEdge,
  deleted_tax_id: DeletedTaxIdEdge,
  deleted_terminal_configuration: DeletedTerminalConfigurationEdge,
  deleted_terminal_location: DeletedTerminalLocationEdge,
  deleted_terminal_reader: DeletedTerminalReaderEdge,
  deleted_test_helpers_test_clock: DeletedTestHelpersTestClockEdge,
  deleted_webhook_endpoint: DeletedWebhookEndpointEdge,
  discount: DiscountEdge,
  dispute: DisputeEdge,
  ephemeral_key: EphemeralKeyEdge,
  event: EventEdge,
  exchange_rate: ExchangeRateEdge,
  external_account: ExternalAccountEdge,
  fee_refund: FeeRefundEdge,
  file: FileEdge,
  file_link: FileLinkEdge,
  financial_connections_account: FinancialConnectionsAccountEdge,
  financial_connections_account_owner: FinancialConnectionsAccountOwnerEdge,
  financial_connections_session: FinancialConnectionsSessionEdge,
  funding_instructions: FundingInstructionsEdge,
  identity_verification_report: IdentityVerificationReportEdge,
  identity_verification_session: IdentityVerificationSessionEdge,
  invoice: InvoiceEdge,
  invoiceitem: InvoiceitemEdge,
  issuing_authorization: IssuingAuthorizationEdge,
  issuing_card: IssuingCardEdge,
  issuing_cardholder: IssuingCardholderEdge,
  issuing_dispute: IssuingDisputeEdge,
  issuing_settlement: IssuingSettlementEdge,
  issuing_transaction: IssuingTransactionEdge,
  item: ItemEdge,
  line_item: LineItemEdge,
  login_link: LoginLinkEdge,
  mandate: MandateEdge,
  payment_intent: PaymentIntentEdge,
  payment_link: PaymentLinkEdge,
  payment_method: PaymentMethodEdge,
  payment_source: PaymentSourceEdge,
  payout: PayoutEdge,
  person: PersonEdge,
  plan: PlanEdge,
  price: PriceEdge,
  product: ProductEdge,
  promotion_code: PromotionCodeEdge,
  quote: QuoteEdge,
  radar_early_fraud_warning: RadarEarlyFraudWarningEdge,
  radar_value_list: RadarValueListEdge,
  radar_value_list_item: RadarValueListItemEdge,
  refund: RefundEdge,
  reporting_report_run: ReportingReportRunEdge,
  reporting_report_type: ReportingReportTypeEdge,
  review: ReviewEdge,
  scheduled_query_run: ScheduledQueryRunEdge,
  setup_attempt: SetupAttemptEdge,
  setup_intent: SetupIntentEdge,
  shipping_rate: ShippingRateEdge,
  source: SourceEdge,
  source_mandate_notification: SourceMandateNotificationEdge,
  source_transaction: SourceTransactionEdge,
  subscription: SubscriptionEdge,
  subscription_item: SubscriptionItemEdge,
  subscription_schedule: SubscriptionScheduleEdge,
  tax_code: TaxCodeEdge,
  tax_id: TaxIdEdge,
  tax_rate: TaxRateEdge,
  terminal_configuration: TerminalConfigurationEdge,
  terminal_connection_token: TerminalConnectionTokenEdge,
  terminal_location: TerminalLocationEdge,
  terminal_reader: TerminalReaderEdge,
  test_helpers_test_clock: TestHelpersTestClockEdge,
  token: TokenEdge,
  topup: TopupEdge,
  transfer: TransferEdge,
  transfer_reversal: TransferReversalEdge,
  treasury_credit_reversal: TreasuryCreditReversalEdge,
  treasury_debit_reversal: TreasuryDebitReversalEdge,
  treasury_financial_account: TreasuryFinancialAccountEdge,
  treasury_financial_account_features: TreasuryFinancialAccountFeaturesEdge,
  treasury_inbound_transfer: TreasuryInboundTransferEdge,
  treasury_outbound_payment: TreasuryOutboundPaymentEdge,
  treasury_outbound_transfer: TreasuryOutboundTransferEdge,
  treasury_received_credit: TreasuryReceivedCreditEdge,
  treasury_received_debit: TreasuryReceivedDebitEdge,
  treasury_transaction: TreasuryTransactionEdge,
  treasury_transaction_entry: TreasuryTransactionEntryEdge,
  webhook_endpoint: WebhookEndpointEdge,
  account_notice: AccountNoticeEdge,
  account_session: AccountSessionEdge,
  application: ApplicationEdge,
  balance_settings: BalanceSettingsEdge,
  billing_alert: BillingAlertEdge,
  billing_alert_triggered: BillingAlertTriggeredEdge,
  billing_credit_balance_summary: BillingCreditBalanceSummaryEdge,
  billing_credit_balance_transaction: BillingCreditBalanceTransactionEdge,
  billing_credit_grant: BillingCreditGrantEdge,
  billing_meter: BillingMeterEdge,
  billing_meter_event: BillingMeterEventEdge,
  billing_meter_event_adjustment: BillingMeterEventAdjustmentEdge,
  billing_meter_event_summary: BillingMeterEventSummaryEdge,
  capital_financing_offer: CapitalFinancingOfferEdge,
  capital_financing_summary: CapitalFinancingSummaryEdge,
  capital_financing_transaction: CapitalFinancingTransactionEdge,
  climate_order: ClimateOrderEdge,
  climate_product: ClimateProductEdge,
  climate_supplier: ClimateSupplierEdge,
  confirmation_token: ConfirmationTokenEdge,
  customer_session: CustomerSessionEdge,
  deleted_application: DeletedApplicationEdge,
  deleted_bank_account: DeletedBankAccountEdge,
  deleted_card: DeletedCardEdge,
  deleted_price: DeletedPriceEdge,
  deleted_product_feature: DeletedProductFeatureEdge,
  entitlements_active_entitlement: EntitlementsActiveEntitlementEdge,
  entitlements_active_entitlement_summary: EntitlementsActiveEntitlementSummaryEdge,
  entitlements_feature: EntitlementsFeatureEdge,
  financial_connections_account_inferred_balance: FinancialConnectionsAccountInferredBalanceEdge,
  financial_connections_account_ownership: FinancialConnectionsAccountOwnershipEdge,
  financial_connections_institution: FinancialConnectionsInstitutionEdge,
  financial_connections_transaction: FinancialConnectionsTransactionEdge,
  forwarding_request: ForwardingRequestEdge,
  fx_quote: FxQuoteEdge,
  invoice_payment: InvoicePaymentEdge,
  invoice_rendering_template: InvoiceRenderingTemplateEdge,
  issuing_credit_underwriting_record: IssuingCreditUnderwritingRecordEdge,
  issuing_dispute_settlement_detail: IssuingDisputeSettlementDetailEdge,
  issuing_fraud_liability_debit: IssuingFraudLiabilityDebitEdge,
  issuing_personalization_design: IssuingPersonalizationDesignEdge,
  issuing_physical_bundle: IssuingPhysicalBundleEdge,
  issuing_token: IssuingTokenEdge,
  margin: MarginEdge,
  order: OrderEdge,
  payment_attempt_record: PaymentAttemptRecordEdge,
  payment_intent_amount_details_line_item: PaymentIntentAmountDetailsLineItemEdge,
  payment_method_configuration: PaymentMethodConfigurationEdge,
  payment_method_domain: PaymentMethodDomainEdge,
  payment_record: PaymentRecordEdge,
  privacy_redaction_job: PrivacyRedactionJobEdge,
  privacy_redaction_job_validation_error: PrivacyRedactionJobValidationErrorEdge,
  product_feature: ProductFeatureEdge,
  quote_line: QuoteLineEdge,
  quote_preview_invoice: QuotePreviewInvoiceEdge,
  quote_preview_subscription_schedule: QuotePreviewSubscriptionScheduleEdge,
  tax_association: TaxAssociationEdge,
  tax_calculation: TaxCalculationEdge,
  tax_calculation_line_item: TaxCalculationLineItemEdge,
  tax_form: TaxFormEdge,
  tax_registration: TaxRegistrationEdge,
  tax_settings: TaxSettingsEdge,
  tax_transaction: TaxTransactionEdge,
  tax_transaction_line_item: TaxTransactionLineItemEdge,
  terminal_reader_collected_data: TerminalReaderCollectedDataEdge,
  terminal_onboarding_link: TerminalOnboardingLinkEdge,
  billing_analytics_meter_usage: BillingAnalyticsMeterUsageEdge,
  billing_analytics_meter_usage_row: BillingAnalyticsMeterUsageRowEdge,
  payment_method_balance: PaymentMethodBalanceEdge,
  delegated_checkout_requested_session: DelegatedCheckoutRequestedSessionEdge,
  identity_blocklist_entry: IdentityBlocklistEntryEdge,
  transit_balance: TransitBalanceEdge,
  issuing_program: IssuingProgramEdge,
  balance_transfer: BalanceTransferEdge,
  radar_account_evaluation: RadarAccountEvaluationEdge,
  product_catalog_trial_offer: ProductCatalogTrialOfferEdge,
};

const defaultNodeWidth = 200;
const defaultNodeHeight = 100;
const nodePadding = 10;

const getNodesAndEdges = (
  data: { [key: string]: StripeResource },
  resourceType: ResourceType | null,
  nodeWidth: number,
  nodeHeight: number,
  selectedNodeId?: string | null,
  highlightedNodeId?: string | null,
  expandedNodes?: string[],
): { nodes: any[]; edges: any[] } => {
  const nodes: any[] = [];
  const edges: any[] = [];

  if (!data || !resourceType) {
    return { nodes, edges };
  }

  // Dummy implementation for placeholder function to allow component rendering.
  // In a real app, this would contain logic to traverse the graph data.

  return { nodes, edges };
};

const ResourceGraphView = () => {
  return (
    <div style={{ height: '600px', border: '1px solid #ccc' }}>
      <p style={{ padding: '20px', textAlign: 'center' }}>Resource Graph View Placeholder</p>
    </div>
  );
};

export default ResourceGraphView;
