
import React, { useState, useEffect, useMemo } from 'react';
import { useTheme } from '@mui/material/styles';
import {
  Box,
  CircularProgress,
  Typography,
  IconButton,
  Tooltip,
  useMediaQuery,
} from '@mui/material';
import ReactFlow, {
  Zoom,
  useNodes,
  useEdges,
  useReactFlow,
  ReactFlowProvider,
  Controls,
  MiniMap,
  Background,
  NodeTypes,
  EdgeTypes,
  addEdge,
  Node,
  Edge,
} from 'reactflow';
// Styles loaded via index.html
// import 'reactflow/dist/style.css';
import {
  ChevronLeft,
  ChevronRight,
  Fullscreen,
  FullscreenExit,
} from '@mui/icons-material';
import {
  useStripeData,
  ResourceType,
  StripeResource,
  NodeData,
  EdgeData,
  isEdge,
  isNode,
} from '../hooks/useStripeData';
import {
  AccountNode,
  AccountLinkNode,
  ApplePayDomainNode,
  ApplicationFeeNode,
  AppsSecretNode,
  BalanceNode,
  BalanceTransactionNode,
  BankAccountNode,
  BillingPortalConfigurationNode,
  BillingPortalSessionNode,
  CapabilityNode,
  CardNode,
  CashBalanceNode,
  ChargeNode,
  CheckoutSessionNode,
  CountrySpecNode,
  CouponNode,
  CreditNoteNode,
  CreditNoteLineItemNode,
  CustomerNode,
  CustomerBalanceTransactionNode,
  CustomerCashBalanceTransactionNode,
  DeletedAccountNode,
  DeletedApplePayDomainNode,
  DeletedCouponNode,
  DeletedCustomerNode,
  DeletedDiscountNode,
  DeletedExternalAccountNode,
  DeletedInvoiceNode,
  DeletedInvoiceitemNode,
  DeletedPaymentSourceNode,
  DeletedPersonNode,
  DeletedPlanNode,
  DeletedProductNode,
  DeletedRadarValueListNode,
  DeletedRadarValueListItemNode,
  DeletedSubscriptionItemNode,
  DeletedTaxIdNode,
  DeletedTerminalConfigurationNode,
  DeletedTerminalLocationNode,
  DeletedTerminalReaderNode,
  DeletedTestHelpersTestClockNode,
  DeletedWebhookEndpointNode,
  DiscountNode,
  DisputeNode,
  EphemeralKeyNode,
  EventNode,
  ExchangeRateNode,
  ExternalAccountNode,
  FeeRefundNode,
  FileNode,
  FileLinkNode,
  FinancialConnectionsAccountNode,
  FinancialConnectionsAccountOwnerNode,
  FinancialConnectionsSessionNode,
  FundingInstructionsNode,
  IdentityVerificationReportNode,
  IdentityVerificationSessionNode,
  InvoiceNode,
  InvoiceitemNode,
  IssuingAuthorizationNode,
  IssuingCardNode,
  IssuingCardholderNode,
  IssuingDisputeNode,
  IssuingSettlementNode,
  IssuingTransactionNode,
  ItemNode,
  LineItemNode,
  LoginLinkNode,
  MandateNode,
  PaymentIntentNode,
  PaymentLinkNode,
  PaymentMethodNode,
  PaymentSourceNode,
  PayoutNode,
  PersonNode,
  PlanNode,
  PriceNode,
  ProductNode,
  PromotionCodeNode,
  QuoteNode,
  RadarEarlyFraudWarningNode,
  RadarValueListNode,
  RadarValueListItemNode,
  RefundNode,
  ReportingReportRunNode,
  ReportingReportTypeNode,
  ReviewNode,
  ScheduledQueryRunNode,
  SetupAttemptNode,
  SetupIntentNode,
  ShippingRateNode,
  SourceNode,
  SourceMandateNotificationNode,
  SourceTransactionNode,
  SubscriptionNode,
  SubscriptionItemNode,
  SubscriptionScheduleNode,
  TaxCodeNode,
  TaxIdNode,
  TaxRateNode,
  TerminalConfigurationNode,
  TerminalConnectionTokenNode,
  TerminalLocationNode,
  TerminalReaderNode,
  TestHelpersTestClockNode,
  TokenNode,
  TopupNode,
  TransferNode,
  TransferReversalNode,
  TreasuryCreditReversalNode,
  TreasuryDebitReversalNode,
  TreasuryFinancialAccountNode,
  TreasuryFinancialAccountFeaturesNode,
  TreasuryInboundTransferNode,
  TreasuryOutboundPaymentNode,
  TreasuryOutboundTransferNode,
  TreasuryReceivedCreditNode,
  TreasuryReceivedDebitNode,
  TreasuryTransactionNode,
  TreasuryTransactionEntryNode,
  WebhookEndpointNode,
  AccountNoticeNode,
  AccountSessionNode,
  ApplicationNode,
  BalanceSettingsNode,
  BillingAlertNode,
  BillingAlertTriggeredNode,
  BillingCreditBalanceSummaryNode,
  BillingCreditBalanceTransactionNode,
  BillingCreditGrantNode,
  BillingMeterNode,
  BillingMeterEventNode,
  BillingMeterEventAdjustmentNode,
  BillingMeterEventSummaryNode,
  CapitalFinancingOfferNode,
  CapitalFinancingSummaryNode,
  CapitalFinancingTransactionNode,
  ClimateOrderNode,
  ClimateProductNode,
  ClimateSupplierNode,
  ConfirmationTokenNode,
  CustomerSessionNode,
  DeletedApplicationNode,
  DeletedBankAccountNode,
  DeletedCardNode,
  DeletedPriceNode,
  DeletedProductFeatureNode,
  EntitlementsActiveEntitlementNode,
  EntitlementsActiveEntitlementSummaryNode,
  EntitlementsFeatureNode,
  FinancialConnectionsAccountInferredBalanceNode,
  FinancialConnectionsAccountOwnershipNode,
  FinancialConnectionsInstitutionNode,
  FinancialConnectionsTransactionNode,
  ForwardingRequestNode,
  FxQuoteNode,
  InvoicePaymentNode,
  InvoiceRenderingTemplateNode,
  IssuingCreditUnderwritingRecordNode,
  IssuingDisputeSettlementDetailNode,
  IssuingFraudLiabilityDebitNode,
  IssuingPersonalizationDesignNode,
  IssuingPhysicalBundleNode,
  IssuingTokenNode,
  MarginNode,
  OrderNode,
  PaymentAttemptRecordNode,
  PaymentIntentAmountDetailsLineItemNode,
  PaymentMethodConfigurationNode,
  PaymentMethodDomainNode,
  PaymentRecordNode,
  PrivacyRedactionJobNode,
  PrivacyRedactionJobValidationErrorNode,
  ProductFeatureNode,
  QuoteLineNode,
  QuotePreviewInvoiceNode,
  QuotePreviewSubscriptionScheduleNode,
  TaxAssociationNode,
  TaxCalculationNode,
  TaxCalculationLineItemNode,
  TaxFormNode,
  TaxRegistrationNode,
  TaxSettingsNode,
  TaxTransactionNode,
  TaxTransactionLineItemNode,
  TerminalReaderCollectedDataNode,
  TerminalOnboardingLinkNode,
  BillingAnalyticsMeterUsageNode,
  BillingAnalyticsMeterUsageRowNode,
  PaymentMethodBalanceNode,
  DelegatedCheckoutRequestedSessionNode,
  IdentityBlocklistEntryNode,
  TransitBalanceNode,
  IssuingProgramNode,
  BalanceTransferNode,
  RadarAccountEvaluationNode,
  ProductCatalogTrialOfferNode,
} from './nodes';
import {
  DefaultEdge,
  AccountEdge,
  AccountLinkEdge,
  ApplePayDomainEdge,
  ApplicationFeeEdge,
  AppsSecretEdge,
  BalanceEdge,
  BalanceTransactionEdge,
  BankAccountEdge,
  BillingPortalConfigurationEdge,
  BillingPortalSessionEdge,
  CapabilityEdge,
  CardEdge,
  CashBalanceEdge,
  ChargeEdge,
  CheckoutSessionEdge,
  CountrySpecEdge,
  CouponEdge,
  CreditNoteEdge,
  CreditNoteLineItemEdge,
  CustomerEdge,
  CustomerBalanceTransactionEdge,
  CustomerCashBalanceTransactionEdge,
  DeletedAccountEdge,
  DeletedApplePayDomainEdge,
  DeletedCouponEdge,
  DeletedCustomerEdge,
  DeletedDiscountEdge,
  DeletedExternalAccountEdge,
  DeletedInvoiceEdge,
  DeletedInvoiceitemEdge,
  DeletedPaymentSourceEdge,
  DeletedPersonEdge,
  DeletedPlanEdge,
  DeletedProductEdge,
  DeletedRadarValueListEdge,
  DeletedRadarValueListItemEdge,
  DeletedSubscriptionItemEdge,
  DeletedTaxIdEdge,
  DeletedTerminalConfigurationEdge,
  DeletedTerminalLocationEdge,
  DeletedTerminalReaderEdge,
  DeletedTestHelpersTestClockEdge,
  DeletedWebhookEndpointEdge,
  DiscountEdge,
  DisputeEdge,
  EphemeralKeyEdge,
  EventEdge,
  ExchangeRateEdge,
  ExternalAccountEdge,
  FeeRefundEdge,
  FileEdge,
  FileLinkEdge,
  FinancialConnectionsAccountEdge,
  FinancialConnectionsAccountOwnerEdge,
  FinancialConnectionsSessionEdge,
  FundingInstructionsEdge,
  IdentityVerificationReportEdge,
  IdentityVerificationSessionEdge,
  InvoiceEdge,
  InvoiceitemEdge,
  IssuingAuthorizationEdge,
  IssuingCardEdge,
  IssuingCardholderEdge,
  IssuingDisputeEdge,
  IssuingSettlementEdge,
  IssuingTransactionEdge,
  ItemEdge,
  LineItemEdge,
  LoginLinkEdge,
  MandateEdge,
  PaymentIntentEdge,
  PaymentLinkEdge,
  PaymentMethodEdge,
  PaymentSourceEdge,
  PayoutEdge,
  PersonEdge,
  PlanEdge,
  PriceEdge,
  ProductEdge,
  PromotionCodeEdge,
  QuoteEdge,
  RadarEarlyFraudWarningEdge,
  RadarValueListEdge,
  RadarValueListItemEdge,
  RefundEdge,
  ReportingReportRunEdge,
  ReportingReportTypeEdge,
  ReviewEdge,
  ScheduledQueryRunEdge,
  SetupAttemptEdge,
  SetupIntentEdge,
  ShippingRateEdge,
  SourceEdge,
  SourceMandateNotificationEdge,
  SourceTransactionEdge,
  SubscriptionEdge,
  SubscriptionItemEdge,
  SubscriptionScheduleEdge,
  TaxCodeEdge,
  TaxIdEdge,
  TaxRateEdge,
  TerminalConfigurationEdge,
  TerminalConnectionTokenEdge,
  TerminalLocationEdge,
  TerminalReaderEdge,
  TestHelpersTestClockEdge,
  TokenEdge,
  TopupEdge,
  TransferEdge,
  TransferReversalEdge,
  TreasuryCreditReversalEdge,
  TreasuryDebitReversalEdge,
  TreasuryFinancialAccountEdge,
  TreasuryFinancialAccountFeaturesEdge,
  TreasuryInboundTransferEdge,
  TreasuryOutboundPaymentEdge,
  TreasuryOutboundTransferEdge,
  TreasuryReceivedCreditEdge,
  TreasuryReceivedDebitEdge,
  TreasuryTransactionEdge,
  TreasuryTransactionEntryEdge,
  WebhookEndpointEdge,
  AccountNoticeEdge,
  AccountSessionEdge,
  ApplicationEdge,
  BalanceSettingsEdge,
  BillingAlertEdge,
  BillingAlertTriggeredEdge,
  BillingCreditBalanceSummaryEdge,
  BillingCreditBalanceTransactionEdge,
  BillingCreditGrantEdge,
  BillingMeterEdge,
  BillingMeterEventEdge,
  BillingMeterEventAdjustmentEdge,
  BillingMeterEventSummaryEdge,
  CapitalFinancingOfferEdge,
  CapitalFinancingSummaryEdge,
  CapitalFinancingTransactionEdge,
  ClimateOrderEdge,
  ClimateProductEdge,
  ClimateSupplierEdge,
  ConfirmationTokenEdge,
  CustomerSessionEdge,
  DeletedApplicationEdge,
  DeletedBankAccountEdge,
  DeletedCardEdge,
  DeletedPriceEdge,
  DeletedProductFeatureEdge,
  EntitlementsActiveEntitlementEdge,
  EntitlementsActiveEntitlementSummaryEdge,
  EntitlementsFeatureEdge,
  FinancialConnectionsAccountInferredBalanceEdge,
  FinancialConnectionsAccountOwnershipEdge,
  FinancialConnectionsInstitutionEdge,
  FinancialConnectionsTransactionEdge,
  ForwardingRequestEdge,
  FxQuoteEdge,
  InvoicePaymentEdge,
  InvoiceRenderingTemplateEdge,
  IssuingCreditUnderwritingRecordEdge,
  IssuingDisputeSettlementDetailEdge,
  IssuingFraudLiabilityDebitEdge,
  IssuingPersonalizationDesignEdge,
  IssuingPhysicalBundleEdge,
  IssuingTokenEdge,
  MarginEdge,
  OrderEdge,
  PaymentAttemptRecordEdge,
  PaymentIntentAmountDetailsLineItemEdge,
  PaymentMethodConfigurationEdge,
  PaymentMethodDomainEdge,
  PaymentRecordEdge,
  PrivacyRedactionJobEdge,
  PrivacyRedactionJobValidationErrorEdge,
  ProductFeatureEdge,
  QuoteLineEdge,
  QuotePreviewInvoiceEdge,
  QuotePreviewSubscriptionScheduleEdge,
  TaxAssociationEdge,
  TaxCalculationEdge,
  TaxCalculationLineItemEdge,
  TaxFormEdge,
  TaxRegistrationEdge,
  TaxSettingsEdge,
  TaxTransactionEdge,
  TaxTransactionLineItemEdge,
  TerminalReaderCollectedDataEdge,
  TerminalOnboardingLinkEdge,
  BillingAnalyticsMeterUsageEdge,
  BillingAnalyticsMeterUsageRowEdge,
  PaymentMethodBalanceEdge,
  DelegatedCheckoutRequestedSessionEdge,
  IdentityBlocklistEntryEdge,
  TransitBalanceEdge,
  IssuingProgramEdge,
  BalanceTransferEdge,
  RadarAccountEvaluationEdge,
  ProductCatalogTrialOfferEdge,
} from './edges';

const nodeTypes: NodeTypes = {
  account: AccountNode,
  account_link: AccountLinkNode,
  apple_pay_domain: ApplePayDomainNode,
  application_fee: ApplicationFeeNode,
  apps_secret: AppsSecretNode,
  balance: BalanceNode,
  balance_transaction: BalanceTransactionNode,
  bank_account: BankAccountNode,
  billing_portal_configuration: BillingPortalConfigurationNode,
  billing_portal_session: BillingPortalSessionNode,
  capability: CapabilityNode,
  card: CardNode,
  cash_balance: CashBalanceNode,
  charge: ChargeNode,
  checkout_session: CheckoutSessionNode,
  country_spec: CountrySpecNode,
  coupon: CouponNode,
  credit_note: CreditNoteNode,
  credit_note_line_item: CreditNoteLineItemNode,
  customer: CustomerNode,
  customer_balance_transaction: CustomerBalanceTransactionNode,
  customer_cash_balance_transaction: CustomerCashBalanceTransactionNode,
  deleted_account: DeletedAccountNode,
  deleted_apple_pay_domain: DeletedApplePayDomainNode,
  deleted_coupon: DeletedCouponNode,
  deleted_customer: DeletedCustomerNode,
  deleted_discount: DeletedDiscountNode,
  deleted_external_account: DeletedExternalAccountNode,
  deleted_invoice: DeletedInvoiceNode,
  deleted_invoiceitem: DeletedInvoiceitemNode,
  deleted_payment_source: DeletedPaymentSourceNode,
  deleted_person: DeletedPersonNode,
  deleted_plan: DeletedPlanNode,
  deleted_product: DeletedProductNode,
  deleted_radar_value_list: DeletedRadarValueListNode,
  deleted_radar_value_list_item: DeletedRadarValueListItemNode,
  deleted_subscription_item: DeletedSubscriptionItemNode,
  deleted_tax_id: DeletedTaxIdNode,
  deleted_terminal_configuration: DeletedTerminalConfigurationNode,
  deleted_terminal_location: DeletedTerminalLocationNode,
  deleted_terminal_reader: DeletedTerminalReaderNode,
  deleted_test_helpers_test_clock: DeletedTestHelpersTestClockNode,
  deleted_webhook_endpoint: DeletedWebhookEndpointNode,
  discount: DiscountNode,
  dispute: DisputeNode,
  ephemeral_key: EphemeralKeyNode,
  event: EventNode,
  exchange_rate: ExchangeRateNode,
  external_account: ExternalAccountNode,
  fee_refund: FeeRefundNode,
  file: FileNode,
  file_link: FileLinkNode,
  financial_connections_account: FinancialConnectionsAccountNode,
  financial_connections_account_owner: FinancialConnectionsAccountOwnerNode,
  financial_connections_session: FinancialConnectionsSessionNode,
  funding_instructions: FundingInstructionsNode,
  identity_verification_report: IdentityVerificationReportNode,
  identity_verification_session: IdentityVerificationSessionNode,
  invoice: InvoiceNode,
  invoiceitem: InvoiceitemNode,
  issuing_authorization: IssuingAuthorizationNode,
  issuing_card: IssuingCardNode,
  issuing_cardholder: IssuingCardholderNode,
  issuing_dispute: IssuingDisputeNode,
  issuing_settlement: IssuingSettlementNode,
  issuing_transaction: IssuingTransactionNode,
  item: ItemNode,
  line_item: LineItemNode,
  login_link: LoginLinkNode,
  mandate: MandateNode,
  payment_intent: PaymentIntentNode,
  payment_link: PaymentLinkNode,
  payment_method: PaymentMethodNode,
  payment_source: PaymentSourceNode,
  payout: PayoutNode,
  person: PersonNode,
  plan: PlanNode,
  price: PriceNode,
  product: ProductNode,
  promotion_code: PromotionCodeNode,
  quote: QuoteNode,
  radar_early_fraud_warning: RadarEarlyFraudWarningNode,
  radar_value_list: RadarValueListNode,
  radar_value_list_item: RadarValueListItemNode,
  refund: RefundNode,
  reporting_report_run: ReportingReportRunNode,
  reporting_report_type: ReportingReportTypeNode,
  review: ReviewNode,
  scheduled_query_run: ScheduledQueryRunNode,
  setup_attempt: SetupAttemptNode,
  setup_intent: SetupIntentNode,
  shipping_rate: ShippingRateNode,
  source: SourceNode,
  source_mandate_notification: SourceMandateNotificationNode,
  source_transaction: SourceTransactionNode,
  subscription: SubscriptionNode,
  subscription_item: SubscriptionItemNode,
  subscription_schedule: SubscriptionScheduleNode,
  tax_code: TaxCodeNode,
  tax_id: TaxIdNode,
  tax_rate: TaxRateNode,
  terminal_configuration: TerminalConfigurationNode,
  terminal_connection_token: TerminalConnectionTokenNode,
  terminal_location: TerminalLocationNode,
  terminal_reader: TerminalReaderNode,
  test_helpers_test_clock: TestHelpersTestClockNode,
  token: TokenNode,
  topup: TopupNode,
  transfer: TransferNode,
  transfer_reversal: TransferReversalNode,
  treasury_credit_reversal: TreasuryCreditReversalNode,
  treasury_debit_reversal: TreasuryDebitReversalNode,
  treasury_financial_account: TreasuryFinancialAccountNode,
  treasury_financial_account_features: TreasuryFinancialAccountFeaturesNode,
  treasury_inbound_transfer: TreasuryInboundTransferNode,
  treasury_outbound_payment: TreasuryOutboundPaymentNode,
  treasury_outbound_transfer: TreasuryOutboundTransferNode,
  treasury_received_credit: TreasuryReceivedCreditNode,
  treasury_received_debit: TreasuryReceivedDebitNode,
  treasury_transaction: TreasuryTransactionNode,
  treasury_transaction_entry: TreasuryTransactionEntryNode,
  webhook_endpoint: WebhookEndpointNode,
  account_notice: AccountNoticeNode,
  account_session: AccountSessionNode,
  application: ApplicationNode,
  balance_settings: BalanceSettingsNode,
  billing_alert: BillingAlertNode,
  billing_alert_triggered: BillingAlertTriggeredNode,
  billing_credit_balance_summary: BillingCreditBalanceSummaryNode,
  billing_credit_balance_transaction: BillingCreditBalanceTransactionNode,
  billing_credit_grant: BillingCreditGrantNode,
  billing_meter: BillingMeterNode,
  billing_meter_event: BillingMeterEventNode,
  billing_meter_event_adjustment: BillingMeterEventAdjustmentNode,
  billing_meter_event_summary: BillingMeterEventSummaryNode,
  capital_financing_offer: CapitalFinancingOfferNode,
  capital_financing_summary: CapitalFinancingSummaryNode,
  capital_financing_transaction: CapitalFinancingTransactionNode,
  climate_order: ClimateOrderNode,
  climate_product: ClimateProductNode,
  climate_supplier: ClimateSupplierNode,
  confirmation_token: ConfirmationTokenNode,
  customer_session: CustomerSessionNode,
  deleted_application: DeletedApplicationNode,
  deleted_bank_account: DeletedBankAccountNode,
  deleted_card: DeletedCardNode,
  deleted_price: DeletedPriceNode,
  deleted_product_feature: DeletedProductFeatureNode,
  entitlements_active_entitlement: EntitlementsActiveEntitlementNode,
  entitlements_active_entitlement_summary: EntitlementsActiveEntitlementSummaryNode,
  entitlements_feature: EntitlementsFeatureNode,
  financial_connections_account_inferred_balance: FinancialConnectionsAccountInferredBalanceNode,
  financial_connections_account_ownership: FinancialConnectionsAccountOwnershipNode,
  financial_connections_institution: FinancialConnectionsInstitutionNode,
  financial_connections_transaction: FinancialConnectionsTransactionNode,
  forwarding_request: ForwardingRequestNode,
  fx_quote: FxQuoteNode,
  invoice_payment: InvoicePaymentNode,
  invoice_rendering_template: InvoiceRenderingTemplateNode,
  issuing_credit_underwriting_record: IssuingCreditUnderwritingRecordNode,
  issuing_dispute_settlement_detail: IssuingDisputeSettlementDetailNode,
  issuing_fraud_liability_debit: IssuingFraudLiabilityDebitNode,
  issuing_personalization_design: IssuingPersonalizationDesignNode,
  issuing_physical_bundle: IssuingPhysicalBundleNode,
  issuing_token: IssuingTokenNode,
  margin: MarginNode,
  order: OrderNode,
  payment_attempt_record: PaymentAttemptRecordNode,
  payment_intent_amount_details_line_item: PaymentIntentAmountDetailsLineItemNode,
  payment_method_configuration: PaymentMethodConfigurationNode,
  payment_method_domain: PaymentMethodDomainNode,
  payment_record: PaymentRecordNode,
  privacy_redaction_job: PrivacyRedactionJobNode,
  privacy_redaction_job_validation_error: PrivacyRedactionJobValidationErrorNode,
  product_feature: ProductFeatureNode,
  quote_line: QuoteLineNode,
  quote_preview_invoice: QuotePreviewInvoiceNode,
  quote_preview_subscription_schedule: QuotePreviewSubscriptionScheduleNode,
  tax_association: TaxAssociationNode,
  tax_calculation: TaxCalculationNode,
  tax_calculation_line_item: TaxCalculationLineItemNode,
  tax_form: TaxFormNode,
  tax_registration: TaxRegistrationNode,
  tax_settings: TaxSettingsNode,
  tax_transaction: TaxTransactionNode,
  tax_transaction_line_item: TaxTransactionLineItemNode,
  terminal_reader_collected_data: TerminalReaderCollectedDataNode,
  terminal_onboarding_link: TerminalOnboardingLinkNode,
  billing_analytics_meter_usage: BillingAnalyticsMeterUsageNode,
  billing_analytics_meter_usage_row: BillingAnalyticsMeterUsageRowNode,
  payment_method_balance: PaymentMethodBalanceNode,
  delegated_checkout_requested_session: DelegatedCheckoutRequestedSessionNode,
  identity_blocklist_entry: IdentityBlocklistEntryNode,
  transit_balance: TransitBalanceNode,
  issuing_program: IssuingProgramNode,
  balance_transfer: BalanceTransferNode,
  radar_account_evaluation: RadarAccountEvaluationNode,
  product_catalog_trial_offer: ProductCatalogTrialOfferNode,
};

const edgeTypes: EdgeTypes = {};

const defaultNodeWidth = 200;
const defaultNodeHeight = 100;
const nodePadding = 10;

const getNodesAndEdges = (
  data: { [key: string]: StripeResource },
  resourceType: ResourceType | null,
  nodeWidth: number,
  nodeHeight: number,
  selectedNodeId?: string | null,
  highlightedNodeId?: string | null,
  expandedNodes?: string[],
): { nodes: any[]; edges: any[] } => {
  const nodes: any[] = [];
  const edges: any[] = [];

  if (!data) {
    return { nodes, edges };
  }

  let yOffset = 0;
  let xOffset = 0;

  // Simple layout logic to prevent overlap and organize nodes
  Object.values(data).forEach((resource, index) => {
    const nodeId = resource.id;
    const type = resource.object; // e.g., 'customer', 'charge'
    
    // Map resource object types to our node types.
    // The keys in nodeTypes are expected to match resource.object (e.g. 'charge', 'customer')
    // or we can add a fallback.
    
    // We add a basic node for the resource
    nodes.push({
      id: nodeId,
      type: type, // This must match keys in nodeTypes
      position: { x: xOffset, y: yOffset },
      data: { label: resource.id, ...resource },
    });

    // Create edges based on relationships found in the resource
    // This is a simplified traversal for demonstration
    if (resource.customer && typeof resource.customer === 'string') {
        edges.push({
            id: `${nodeId}-${resource.customer}`,
            source: resource.customer, // source is customer
            target: nodeId, // target is current resource (e.g. charge belonging to customer)
            type: 'default',
        });
    }
    
    if (resource.charge && typeof resource.charge === 'string') {
        // e.g. Invoice -> Charge
         edges.push({
            id: `${nodeId}-${resource.charge}`,
            source: nodeId,
            target: resource.charge,
            type: 'default',
        });
    }

    // Grid layout adjustments
    xOffset += 300;
    if ((index + 1) % 4 === 0) {
        xOffset = 0;
        yOffset += 200;
    }
  });

  return { nodes, edges };
};

const ResourceGraphView = () => {
    const { data, loading, error } = useStripeData();
    const [nodes, setNodes] = useState<Node[]>([]);
    const [edges, setEdges] = useState<Edge[]>([]);
    
    useEffect(() => {
        if(data) {
            const { nodes: n, edges: e } = getNodesAndEdges(data, null, 200, 100);
            setNodes(n);
            setEdges(e);
        }
    }, [data]);

    if(loading) return <div className="flex justify-center items-center h-full"><CircularProgress /></div>;
    if(error) return <div className="text-red-500 p-4">Error: {error}</div>;

    return (
        <div style={{ height: '800px', border: '1px solid #333', borderRadius: '8px', overflow: 'hidden' }}>
            <ReactFlowProvider>
                <ReactFlow
                    nodes={nodes}
                    edges={edges}
                    nodeTypes={nodeTypes}
                    edgeTypes={edgeTypes}
                    fitView
                    attributionPosition="bottom-right"
                >
                    <Background color="#aaa" gap={16} />
                    <Controls />
                    <MiniMap />
                </ReactFlow>
            </ReactFlowProvider>
        </div>
    );
}

export default ResourceGraphView;
